const express = require('express')
const router = express.Router()
const catchAsync = require('../utils/catchAsync')
const Review = require('../models/Review')
const Recipe = require('../models/Recipe')
const isLoggedIn = require('../middleware')
const {postReview,deleteReview} = require('../controllers/Reviews')
router.post('/recipe/:id/reviews',isLoggedIn,postReview)
 router.delete('/recipe/:id/reviews/:reviewId',isLoggedIn,deleteReview)
 module.exports= router 